first_commit
Saffica/wish-to-learn pull request #8
Opened 2023-03-21 22:26 UTC by maksimSushko

Заранее прошу прощения :)

2023-03-24 21:29 UTC, Saffica requested changes

2023-03-24 21:29 UTC, Saffica commented on frontend/src/App.js
> +import {BrowserRouter} from 'react-router-dom';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/App.js
> +import {Header} from './components/Header';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/App.js
> +
зачем добавлен пропуск строки?

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/AppRouter.js
> +import {Login} from "./Login";
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Header.jsx
> +import {Logo} from './Logo';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Header.jsx
> +import {Navbar} from './Navbar';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Header.jsx
> +import {Login} from './Login';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Header.jsx
> +            style={{backgroundColor: '#42597B', width: '100%', padding: '10px'}}>
Вместо применения инлайн стилей в элементах, лучше вынести их в отдельные файлы стилей, чтобы код был более читаемым и управляемым.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Header.jsx
> +                style={{
Вместо применения инлайн стилей в элементах, лучше вынести их в отдельные файлы стилей, чтобы код был более читаемым и управляемым.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Header.jsx
> +export const Header = () => {
header и logo не будут переиспользоваться, сделай вложенными компонентами, чтоб уменьшить количество компонентов на верхнем уровне

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Login.jsx
> +                style={{
Вместо применения инлайн стилей в элементах, лучше вынести их в отдельные файлы стилей, чтобы код был более читаемым и управляемым.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Logo.jsx
> +export const Logo = ({height, width}) => {
добавить проверку на undefined, чтобы не получать ошибку при использовании компонента без передачи этих пропсов.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Navbar.jsx
> +            style={{width: '100%', display: 'flex', justifyContent: 'start', marginLeft: '50px'}}>
Вместо применения инлайн стилей в элементах, лучше вынести их в отдельные файлы стилей, чтобы код был более читаемым и управляемым.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/NavbarItem.jsx
> +                style={{
Вместо применения инлайн стилей в элементах, лучше вынести их в отдельные файлы стилей, чтобы код был более читаемым и управляемым.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Login.jsx
> +import {Link} from 'react-router-dom';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Logo.jsx
> +import {Link} from 'react-router-dom';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/Navbar.jsx
> +import {NavbarItems} from './NavbarItems';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/NavbarItem.jsx
> +import {Link} from 'react-router-dom';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/NavbarItem.jsx
> +export const NavbarItem = ({item}) => {
добавить проверку на undefined, чтобы не получать ошибку при использовании компонента без передачи этих пропсов.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/NavbarItems.jsx
> +export const NavbarItems = ({items}) => {
добавить проверку на undefined, чтобы не получать ошибку при использовании компонента без передачи этих пропсов.

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/NavbarItems.jsx
> +import {NavbarItem} from './NavbarItem';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/components/NavbarItems.jsx
> +            style={{display: 'flex', justifyContent: 'space-between', gap: '30px'}}>
убрать инлайн стили..)

2023-03-24 21:29 UTC, Saffica commented on frontend/src/routes.js
> +import {Login} from './components/Login';
отсутствуют отступы

2023-03-24 21:29 UTC, Saffica commented on frontend/src/routes.js
> +import {COURSES_ROUTE, COURSE_ROUTE, LOGIN_ROUTE} from './utils/consts';
отсутствуют отступы

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/App.js
> +import {BrowserRouter} from 'react-router-dom';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/App.js
> +import {Header} from './components/Header';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/App.js
> +
Убрал

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/AppRouter.js
> +import {Login} from "./Login";
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Header.jsx
> +import {Logo} from './Logo';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Header.jsx
> +import {Navbar} from './Navbar';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Header.jsx
> +import {Login} from './Login';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Login.jsx
> +import {Link} from 'react-router-dom';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Logo.jsx
> +import {Link} from 'react-router-dom';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Navbar.jsx
> +import {NavbarItems} from './NavbarItems';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/NavbarItem.jsx
> +import {Link} from 'react-router-dom';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/NavbarItems.jsx
> +import {NavbarItem} from './NavbarItem';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/routes.js
> +import {Login} from './components/Login';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/routes.js
> +import {COURSES_ROUTE, COURSE_ROUTE, LOGIN_ROUTE} from './utils/consts';
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Header.jsx
> +export const Header = () => {
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Header.jsx
> +            style={{backgroundColor: '#42597B', width: '100%', padding: '10px'}}>
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Header.jsx
> +                style={{
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Login.jsx
> +                style={{
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Navbar.jsx
> +            style={{width: '100%', display: 'flex', justifyContent: 'start', marginLeft: '50px'}}>
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/Logo.jsx
> +export const Logo = ({height, width}) => {
исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/NavbarItem.jsx
> +export const NavbarItem = ({item}) => {
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/NavbarItem.jsx
> +                style={{
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/NavbarItems.jsx
> +export const NavbarItems = ({items}) => {
Исправил

2023-03-25 19:34 UTC, maksimSushko commented on frontend/src/components/NavbarItems.jsx
> +            style={{display: 'flex', justifyContent: 'space-between', gap: '30px'}}>
Исправил

2023-03-29 19:48 UTC, Saffica approved these changes

2023-03-29 19:49 UTC, merged